-- EthioLink — migration 0001: bootstrap extensions.
--
-- This is the first migration. It does not create any tables; it only enables
-- the PostgreSQL extensions every subsequent migration relies on:
--
--   * pgcrypto — gen_random_uuid() for primary keys (see DATABASE_SCHEMA.md
--     "Conventions"). We deliberately avoid uuid-ossp; pgcrypto is in
--     mainline contrib and is what Amazon RDS PostgreSQL ships with.
--   * citext   — case-insensitive text, used by users.email so that
--     "Hhenok@..." and "hhenok@..." cannot register as two accounts.
--
-- Migrations are forward-only. To remove an extension, write a new
-- compensating migration; do not edit this file after it has been applied
-- in any environment.

BEGIN;

CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS citext;

COMMIT;
